name: overnode

services:

  overgate:
    build:
      context: .
      dockerfile: overgate/Dockerfile
    networks: [backend]

  oversite:
    build:
      context: .
      dockerfile: oversite/Dockerfile
    networks: [backend]

networks:
  backend:
