name: overnode

services:

  overgate:
    build:
      context: .
      dockerfile: overgate/Dockerfile
    environment:
      PROXYF__LISTEN_ON: ":2080"
      PROXYF__LOCAL_SITE: http://oversite:8000
    depends_on:
      - oversite
    networks: [backend]

  oversite:
    build:
      context: .
      dockerfile: oversite/Dockerfile
    environment:
      HTTPD__LISTEN_ON: ":8000"
      HTTPD__SITE_PATH: /site
    volumes:
      - oversite-site:/site:ro
    networks: [backend]

networks:
  backend:

volumes:
  oversite-site:
    driver_opts:
      type: none
      o: bind
      device: ${OVERSITE_SITE_PATH:-${PWD}/.local/var/www/html}
