FROM golang:1.25-alpine@sha256:1ae0735f00daffa3aaf1363a5184c0d2dc55c78e3db4ec70241cdac97bf84b59 AS build
RUN apk add --no-cache git
WORKDIR /src
RUN git clone https://github.com/yggdrasil-network/yggstack.git . && \
    git checkout --detach c39db65e5bccac4cbcf712331a87ea1952cca98b
RUN CGO_ENABLED=0 go build -trimpath -o /out/yggstack ./cmd/yggstack

FROM alpine:3.23@sha256:fd791d74b68913cbb027c6546007b3f0d3bc45125f797758156952bc2d6daf40
RUN apk add --no-cache ca-certificates curl
COPY --from=build /out/yggstack /usr/local/bin/yggstack
USER 65532:65532
ENTRYPOINT ["/usr/local/bin/yggstack"]
